Fixed sound, and clean up
tes3mp-scripts/DoorFramework pull request #1
Opened 2020-04-12 05:28 UTC by dsk80004

The sound files were not being set properly with function spawn.
some commands would post messages twice when only one was required.
aligned the suggested commands in order of which a player would likely use them

2020-04-13 12:06 UTC, uramer commented on main.lua
> +                messageCmdUsage(pid, "Model path is not set!\n")
Type in the message

2020-04-13 12:07 UTC, uramer requested changes
Fix typo in sound message, and I will approve the PR

Thank you!

2020-04-16 09:08 UTC, dsk80004 commented
dh doesn't work, i believe they updated it?

2020-04-16 09:31 UTC, uramer commented
Would be nice if you removed the todo, as this is my repo and I personally don't plan to do that in the near future

2020-04-16 21:33 UTC, dsk80004 commented
You got it, sorry I thought I was only requesting patch to the lua.

2020-05-03 19:49 UTC, uramer approved these changes

2020-05-03 19:49 UTC, merged